#!/usr/bin/env bash
# Homelab Dashboard installer for Linux servers.
#   ./install.sh            interactive first-time setup, then build + start
#   ./install.sh --update   rebuild and restart with the existing .env
set -euo pipefail
cd "$(dirname "$0")"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
warn() { printf '\033[33m  ! %s\033[0m\n' "$*"; }
die()  { printf '\033[31m  ✗ %s\033[0m\n' "$*" >&2; exit 1; }

UPDATE=0
[[ "${1:-}" == "--update" ]] && UPDATE=1

bold "Homelab Dashboard installer"

# ---------- pick a container engine ----------
if command -v docker >/dev/null && docker compose version >/dev/null 2>&1; then
  ENGINE=docker; COMPOSE=(docker compose)
elif command -v podman >/dev/null && podman compose version >/dev/null 2>&1; then
  ENGINE=podman; COMPOSE=(podman compose)
elif command -v podman-compose >/dev/null; then
  ENGINE=podman; COMPOSE=(podman-compose)
elif command -v docker-compose >/dev/null; then
  ENGINE=docker; COMPOSE=(docker-compose)
else
  die "No container engine found. Install Docker (with the compose plugin) or Podman + podman-compose."
fi
info "Using $ENGINE (${COMPOSE[*]})"

# ---------- work out the API socket for the Docker widget ----------
detect_socket() {
  if [[ $ENGINE == docker ]]; then
    [[ -S /var/run/docker.sock ]] && { echo /var/run/docker.sock; return; }
  else
    local uid; uid=$(id -u)
    [[ -S /run/user/$uid/podman/podman.sock ]] && { echo "/run/user/$uid/podman/podman.sock"; return; }
    [[ -S /run/podman/podman.sock ]] && { echo /run/podman/podman.sock; return; }
    if [[ $uid -ne 0 ]]; then
      systemctl --user enable --now podman.socket >/dev/null 2>&1 || true
      [[ -S /run/user/$uid/podman/podman.sock ]] && { echo "/run/user/$uid/podman/podman.sock"; return; }
    fi
  fi
  echo ""
}

if [[ $UPDATE -eq 0 && ! -f .env ]]; then
  bold "First-time setup"
  read -rp "  Dashboard username [admin]: " DUSER; DUSER=${DUSER:-admin}
  read -rsp "  Dashboard password (blank = generate): " DPASS; echo
  if [[ -z "$DPASS" ]]; then
    DPASS=$(head -c 12 /dev/urandom | base64 | tr -d '/+=' | cut -c1-14)
    GENERATED=1
  fi
  read -rp "  Port to listen on [8080]: " DPORT; DPORT=${DPORT:-8080}
  read -rp "  Timezone [$(cat /etc/timezone 2>/dev/null || echo UTC)]: " DTZ
  DTZ=${DTZ:-$(cat /etc/timezone 2>/dev/null || echo UTC)}

  SOCK=$(detect_socket)
  if [[ -n "$SOCK" ]]; then
    info "Container socket: $SOCK"
  else
    warn "No container socket found — the Docker widget will be unavailable until you set CONTAINER_SOCKET in .env"
    SOCK=/var/run/docker.sock
  fi

  # LAN IP so "localhost" in widget URLs resolves to this machine
  LANIP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')

  cat > .env <<EOF
# Generated by install.sh on $(date -Iseconds)
DASH_USER=$DUSER
DASH_PASSWORD=$DPASS
DASH_PORT=$DPORT
SESSION_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
TZ=$DTZ

# Container engine socket for the Docker widget
CONTAINER_SOCKET=$SOCK

# "localhost" in a widget URL is rewritten to this host
HOST_ALIAS=${LANIP:-host.docker.internal}

# Accept self-signed certificates on services you add (Proxmox, TrueNAS, UniFi…)
ALLOW_SELF_SIGNED=true

# Optional: GitHub token for bookmark repo stats (stars / issues / commits)
# GITHUB_TOKEN=
EOF
  chmod 600 .env
  info "Wrote .env"
fi

[[ -f .env ]] || die ".env is missing — run without --update to create it."
# shellcheck disable=SC1091
set -a; . ./.env; set +a

mkdir -p data
# Rootless Podman maps container root to your user; make sure /data is writable either way.
chmod 777 data 2>/dev/null || true

bold "Building (first build takes a few minutes: go2rtc + pytapo + the web app)"
"${COMPOSE[@]}" build
bold "Starting"
"${COMPOSE[@]}" up -d

IP=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')
bold "URL      http://${IP:-localhost}:${DASH_PORT:-8080}"
info "Username ${DASH_USER}"
if [[ -n "${GENERATED:-}" ]]; then bold "Password ${DASH_PASSWORD}   (saved in .env)"; else info "Password (the one you set, saved in .env)"; fi

# ---------- wait for health ----------
printf '  waiting for the dashboard'
for _ in $(seq 1 45); do
  if curl -fsS "http://127.0.0.1:${DASH_PORT:-8080}/healthz" >/dev/null 2>&1; then
    printf ' ok\n'; HEALTHY=1; break
  fi
  printf '.'; sleep 2
done
echo
if [[ -z "${HEALTHY:-}" ]]; then
  warn "No answer on /healthz yet — it may still be starting. Check: ${COMPOSE[*]} logs -f"
else
  bold "Ready."
fi

cat <<EOF

  Useful commands
    ${COMPOSE[*]} logs -f          follow logs
    ${COMPOSE[*]} restart          restart
    ${COMPOSE[*]} down             stop
    ./install.sh --update          rebuild after changing code

  Start on boot
    Docker : already handled (restart: unless-stopped)
    Podman : ./install.sh --systemd   # installs a user service
EOF

# ---------- optional: podman user service ----------
if [[ "${1:-}" == "--systemd" || "${2:-}" == "--systemd" ]]; then
  UNIT="$HOME/.config/systemd/user/homelab-dashboard.service"
  mkdir -p "$(dirname "$UNIT")"
  cat > "$UNIT" <<EOF
[Unit]
Description=Homelab Dashboard
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$(pwd)
EnvironmentFile=$(pwd)/.env
ExecStart=$(command -v ${COMPOSE[0]}) ${COMPOSE[*]:1} up -d
ExecStop=$(command -v ${COMPOSE[0]}) ${COMPOSE[*]:1} down
TimeoutStartSec=0

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  systemctl --user enable --now homelab-dashboard.service
  loginctl enable-linger "$USER" >/dev/null 2>&1 || warn "Run: sudo loginctl enable-linger $USER  (so it starts without login)"
  bold "systemd user service installed"
fi
