import { LinkWidget, ClockWidget, WeatherWidget, GenericWidget } from './basic.jsx';
import { DockerWidget, SystemWidget } from './server.jsx';
import { PlexWidget, WeaverWidget, ScryerWidget, TorrentWidget } from './media.jsx';
import { PrometheusWidget } from './prometheus.jsx';
import { ScryerWantedWidget } from './scryerWanted.jsx';
import { TapoWidget } from './tapo.jsx';
import { APP_WIDGETS, APP_CATEGORIES } from './apps.js';
import {
  UptimeKumaWidget, DnsWidget, ProxmoxWidget, TailscaleWidget, SpeedtestWidget, ArrWidget,
  JellyfinWidget, SeerrWidget, HomeAssistantWidget, ImmichWidget,
} from './services.jsx';

/**
 * Field kinds: text | url | secret | number | select | checkbox | textarea | list
 * `secret` fields are stored server-side only; the UI only ever sees "__SECRET__".
 * `url` on a widget (top-level, not config) is where a click on the card goes.
 */
export const WIDGETS = {
  link: {
    name: 'Bookmark',
    description: 'A clickable tile that opens a URL.',
    component: LinkWidget,
    defaultW: 1,
    defaultTitle: 'New bookmark',
    fields: [
      { key: 'url', label: 'URL', kind: 'url', required: true, placeholder: 'https://…' },
      { key: 'subtitle', label: 'Subtitle', kind: 'text', placeholder: 'Defaults to the hostname' },
      {
        key: 'icon',
        label: 'Icon',
        kind: 'text',
        placeholder: 'plex, sonarr, proxmox… or an emoji, or an image URL',
        hint: 'Names from the dashboard-icons set (github.com/homarr-labs/dashboard-icons); use e.g. github-light for dark logos.',
      },
      { key: 'ping', label: 'Show latency & up/down status', kind: 'checkbox', default: true },
      { key: 'pingUrl', label: 'Ping URL', kind: 'url', placeholder: 'Only if different from the URL above (e.g. an internal address)' },
      { key: 'github', label: 'GitHub: show stars, issues and commits for github.com repo links', kind: 'checkbox', default: true },
      { key: 'token', label: 'GitHub token', kind: 'secret', hint: 'optional — private repos / higher rate limit; or set GITHUB_TOKEN in .env' },
    ],
  },
  clock: {
    icon: '⏱',
    name: 'Clock',
    description: 'Time and date, optionally for another timezone.',
    component: ClockWidget,
    defaultW: 1,
    defaultTitle: 'Clock',
    fields: [
      { key: 'timezone', label: 'Timezone', kind: 'text', placeholder: 'e.g. Europe/London (blank = local)' },
      { key: 'h24', label: '24-hour clock', kind: 'checkbox', default: true },
    ],
  },
  weather: {
    icon: '🌤',
    name: 'Weather',
    description: 'Current conditions + 5-day forecast (Open-Meteo, no key needed).',
    component: WeatherWidget,
    defaultW: 2,
    defaultTitle: 'Weather',
    fields: [
      { key: 'label', label: 'Location name', kind: 'text', placeholder: 'Home' },
      { key: 'lat', label: 'Latitude', kind: 'number', required: true, placeholder: '51.5' },
      { key: 'lon', label: 'Longitude', kind: 'number', required: true, placeholder: '-0.12' },
      { key: 'units', label: 'Units', kind: 'select', options: [['celsius', '°C'], ['fahrenheit', '°F']], default: 'celsius' },
    ],
  },
  docker: {
    icon: 'docker',
    name: 'Docker',
    description: 'Containers on this server with CPU and memory.',
    component: DockerWidget,
    defaultW: 2,
    defaultTitle: 'Docker',
    fields: [
      { key: 'max', label: 'Containers to list', kind: 'number', default: 8 },
      { key: 'stats', label: 'Collect CPU/memory (slower on big hosts)', kind: 'checkbox', default: true },
      { key: 'controls', label: 'Allow start / stop / restart and log viewing from the dashboard', kind: 'checkbox', default: false },
    ],
  },
  system: {
    icon: '🖥',
    name: 'Server',
    description: 'CPU, memory, disk and uptime of the host.',
    component: SystemWidget,
    defaultW: 2,
    defaultTitle: 'Server',
    fields: [
      { key: 'hostname', label: 'Display name', kind: 'text', placeholder: 'Defaults to container hostname' },
      { key: 'disks', label: 'Disk mount points', kind: 'list', placeholder: '/, /mnt/media', default: ['/'] },
    ],
  },
  plex: {
    icon: 'plex',
    name: 'Plex',
    description: 'Now playing, library sizes and recently added.',
    component: PlexWidget,
    defaultW: 2,
    defaultTitle: 'Plex',
    fields: [
      { key: 'url', label: 'Server URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:32400' },
      {
        key: 'token',
        label: 'X-Plex-Token',
        kind: 'secret',
        required: true,
        hint: 'Plex Web → any item → ⋯ → Get Info → View XML; the token is in the URL.',
      },
      { key: 'recent', label: 'Show recently added when idle', kind: 'checkbox', default: true },
    ],
  },
  scryerwanted: {
    icon: '🔍',
    name: 'Scryer · Missing search',
    description: 'Lists every title with missing items, searches all of them in one go and reports what was found or skipped, live.',
    component: ScryerWantedWidget,
    defaultW: 2,
    defaultTitle: 'Missing in Scryer',
    fields: [
      { key: 'url', label: 'Scryer URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:8080' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'needs permission to trigger searches' },
      { key: 'facet', label: 'Only search', kind: 'select', options: [['ALL', 'Everything'], ['MOVIE', 'Movies'], ['SERIES', 'Series'], ['ANIME', 'Anime']], default: 'ALL' },
      { key: 'show', label: 'Titles to show before "show all"', kind: 'number', default: 8 },
      { key: 'limit', label: 'Max missing items to load', kind: 'number', default: 2000 },
    ],
  },
  weaver: {
    icon: '📡',
    name: 'Weaver',
    description: 'Usenet queue, speed and status from Weaver.',
    component: WeaverWidget,
    defaultW: 2,
    defaultTitle: 'Weaver',
    fields: [
      { key: 'url', label: 'Weaver URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:6789' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'Weaver → Settings → API keys. Sent as x-api-key.' },
      { key: 'metrics', label: 'Also read Prometheus metrics (disk space, bandwidth cap)', kind: 'checkbox', default: true },
    ],
  },
  scryer: {
    icon: '🔮',
    name: 'Scryer',
    description: 'Library counts, activity, download queue and upcoming episodes.',
    component: ScryerWidget,
    defaultW: 2,
    defaultTitle: 'Scryer',
    fields: [
      { key: 'url', label: 'Scryer URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:7878' },
      {
        key: 'apiKey',
        label: 'API key',
        kind: 'secret',
        required: true,
        hint: 'Scryer → your profile → API keys (starts with ska_). Sent as a Bearer token.',
      },
      { key: 'view', label: 'Focus', kind: 'select', options: [['overview', 'Queue first'], ['calendar', 'Upcoming episodes first']], default: 'overview' },
      {
        key: 'metrics',
        label: 'Also read Prometheus metrics (storage, client/indexer health, uptime)',
        kind: 'checkbox',
        default: true,
      },
    ],
  },
  qbittorrent: {
    icon: 'qbittorrent',
    name: 'qBittorrent',
    description: 'Transfer speeds and active torrents.',
    component: TorrentWidget,
    defaultW: 2,
    defaultTitle: 'qBittorrent',
    fields: [
      { key: 'url', label: 'WebUI URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:8080' },
      { key: 'username', label: 'Username', kind: 'text' },
      { key: 'password', label: 'Password', kind: 'secret' },
    ],
  },
  transmission: {
    icon: 'transmission',
    name: 'Transmission',
    description: 'Transfer speeds and active torrents.',
    component: TorrentWidget,
    defaultW: 2,
    defaultTitle: 'Transmission',
    fields: [
      { key: 'url', label: 'URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:9091' },
      { key: 'username', label: 'Username', kind: 'text' },
      { key: 'password', label: 'Password', kind: 'secret' },
    ],
  },
  prometheus: {
    icon: 'prometheus',
    name: 'Prometheus',
    description: 'Pick metrics from any /metrics endpoint — Scryer, Weaver, node_exporter, cAdvisor…',
    component: PrometheusWidget,
    defaultW: 2,
    defaultTitle: 'Metrics',
    fields: [
      { key: 'endpoint', label: 'Metrics URL', kind: 'url', required: true, placeholder: 'http://host:port/metrics' },
      {
        key: 'headers',
        label: 'Headers (one per line, stored server-side)',
        kind: 'secret-textarea',
        placeholder: 'Authorization: Bearer ska_…',
        hint: 'Scryer and Weaver both take their API key as a Bearer token here',
      },
      { key: 'metrics', label: 'Metrics to show', kind: 'metrics', hint: 'Test connection lists the metric names available' },
    ],
  },
  uptimekuma: {
    icon: 'uptime-kuma',
    name: 'Uptime Kuma',
    description: 'Monitor status and response times from Uptime Kuma.',
    component: UptimeKumaWidget,
    defaultW: 2,
    defaultTitle: 'Uptime Kuma',
    fields: [
      { key: 'url', label: 'Uptime Kuma URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:3001' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'Settings → API Keys (used for the /metrics endpoint)' },
      { key: 'max', label: 'Monitors to list', kind: 'number', default: 8 },
    ],
  },
  pihole: {
    icon: 'pi-hole',
    name: 'Pi-hole',
    description: 'Queries, blocked count and percentage. Works with v6 and v5.',
    component: DnsWidget,
    defaultW: 2,
    defaultTitle: 'Pi-hole',
    fields: [
      { key: 'url', label: 'Pi-hole URL', kind: 'url', required: true, placeholder: 'http://192.168.1.2' },
      { key: 'password', label: 'Password (v6) / app password', kind: 'secret', hint: 'v6 web password' },
      { key: 'apiKey', label: 'API token (v5 only)', kind: 'secret', hint: 'Settings → API → Show API token' },
    ],
  },
  adguard: {
    icon: 'adguard-home',
    name: 'AdGuard Home',
    description: 'Queries, blocked count, average latency.',
    component: DnsWidget,
    defaultW: 2,
    defaultTitle: 'AdGuard',
    fields: [
      { key: 'url', label: 'AdGuard URL', kind: 'url', required: true, placeholder: 'http://192.168.1.2:3000' },
      { key: 'username', label: 'Username', kind: 'text' },
      { key: 'password', label: 'Password', kind: 'secret' },
    ],
  },
  proxmox: {
    icon: 'proxmox',
    name: 'Proxmox VE',
    description: 'Nodes, VMs, containers and storage.',
    component: ProxmoxWidget,
    defaultW: 2,
    defaultTitle: 'Proxmox',
    fields: [
      { key: 'url', label: 'Proxmox URL', kind: 'url', required: true, placeholder: 'https://192.168.1.5:8006' },
      { key: 'tokenId', label: 'Token ID', kind: 'text', required: true, placeholder: 'user@pam!dashboard' },
      { key: 'apiKey', label: 'Token secret', kind: 'secret', required: true, hint: 'Datacenter → Permissions → API Tokens (PVEAuditor role is enough)' },
      { key: 'max', label: 'Guests to list', kind: 'number', default: 8 },
    ],
  },
  tailscale: {
    icon: 'tailscale',
    name: 'Tailscale',
    description: 'Devices on your tailnet and who is online.',
    component: TailscaleWidget,
    defaultW: 2,
    defaultTitle: 'Tailscale',
    fields: [
      { key: 'apiKey', label: 'API access token', kind: 'secret', required: true, hint: 'login.tailscale.com → Settings → Keys' },
      { key: 'tailnet', label: 'Tailnet', kind: 'text', placeholder: '- (default tailnet)' },
      { key: 'max', label: 'Devices to list', kind: 'number', default: 8 },
    ],
  },
  speedtest: {
    icon: 'speedtest-tracker',
    name: 'Speedtest',
    description: 'Latest result from Speedtest Tracker.',
    component: SpeedtestWidget,
    defaultW: 1,
    defaultTitle: 'Speedtest',
    fields: [
      { key: 'url', label: 'Speedtest Tracker URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:8765' },
      { key: 'apiKey', label: 'API token', kind: 'secret', hint: 'Settings → API tokens' },
    ],
  },
  sonarr: {
    icon: 'sonarr',
    name: 'Sonarr',
    description: 'Queue, missing episodes, this week\'s calendar.',
    component: ArrWidget,
    defaultW: 2,
    defaultTitle: 'Sonarr',
    fields: [
      { key: 'url', label: 'Sonarr URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:8989' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'Settings → General' },
    ],
  },
  radarr: {
    icon: 'radarr',
    name: 'Radarr',
    description: 'Queue, missing movies, upcoming releases.',
    component: ArrWidget,
    defaultW: 2,
    defaultTitle: 'Radarr',
    fields: [
      { key: 'url', label: 'Radarr URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:7878' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'Settings → General' },
    ],
  },
  jellyfin: {
    icon: 'jellyfin',
    name: 'Jellyfin / Emby',
    description: 'Now playing and library counts.',
    component: JellyfinWidget,
    defaultW: 2,
    defaultTitle: 'Jellyfin',
    fields: [
      { key: 'url', label: 'Server URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:8096' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'Dashboard → API Keys' },
    ],
  },
  seerr: {
    icon: 'jellyseerr',
    name: 'Jellyseerr / Overseerr',
    description: 'Pending requests and recent activity.',
    component: SeerrWidget,
    defaultW: 2,
    defaultTitle: 'Requests',
    fields: [
      { key: 'url', label: 'URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:5055' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'Settings → General' },
    ],
  },
  homeassistant: {
    icon: 'home-assistant',
    name: 'Home Assistant',
    description: 'Show sensors and toggle switches/lights.',
    component: HomeAssistantWidget,
    defaultW: 2,
    defaultTitle: 'Home',
    fields: [
      { key: 'url', label: 'Home Assistant URL', kind: 'url', required: true, placeholder: 'http://homeassistant.local:8123' },
      { key: 'apiKey', label: 'Long-lived access token', kind: 'secret', required: true, hint: 'your profile → Security → Long-lived access tokens' },
      { key: 'entities', label: 'Entity ids', kind: 'list', placeholder: 'sensor.office_temperature, switch.desk_lamp, light.kitchen' },
      { key: 'controls', label: 'Allow toggling switches and lights', kind: 'checkbox', default: true },
    ],
  },
  immich: {
    icon: 'immich',
    name: 'Immich',
    description: 'Photo/video counts and storage.',
    component: ImmichWidget,
    defaultW: 2,
    defaultTitle: 'Immich',
    fields: [
      { key: 'url', label: 'Immich URL', kind: 'url', required: true, placeholder: 'http://192.168.1.10:2283' },
      { key: 'apiKey', label: 'API key', kind: 'secret', required: true, hint: 'Account settings → API Keys' },
    ],
  },
  tapo: {
    icon: 'tp-link',
    name: 'Tapo cameras',
    description: 'TP-Link Tapo cameras (incl. battery cams via the H200 hub): cached snapshot, battery, recent events, and live view on demand.',
    component: TapoWidget,
    defaultW: 2,
    defaultTitle: 'Cameras',
    fields: [
      { key: 'host', label: 'Camera or hub IP', kind: 'text', required: true, placeholder: '192.168.1.60 (H200 hub lists all its cameras)' },
      {
        key: 'auth',
        label: 'Login with',
        kind: 'select',
        options: [
          ['cloud', 'TP-Link ID password (the free app login — works for hubs & battery cams)'],
          ['camera', 'Camera Account (Advanced → Camera Account; wired cameras only)'],
        ],
        default: 'cloud',
        hint: 'both are local-only; no TP-Link cloud service or Tapo Care needed',
      },
      { key: 'email', label: 'TP-Link ID email', kind: 'text', placeholder: 'you@example.com — newer firmware (KLAP) needs it', hint: 'stays on your LAN' },
      { key: 'user', label: 'Camera Account username', kind: 'text', placeholder: 'only for Camera Account mode' },
      { key: 'password', label: 'Password', kind: 'secret', required: true },
      { key: 'substream', label: 'Use the low-res substream for live view (lighter on battery/bandwidth)', kind: 'checkbox', default: false },
      { key: 'events', label: 'Events to show per camera', kind: 'number', default: 6 },
      { key: 'hours', label: 'Look back (hours)', kind: 'number', default: 24 },
      { key: 'eventPhotos', label: 'Capture a photo when a new event is detected (one grab per refresh, kept for the last 50 events)', kind: 'checkbox', default: true },
      { key: 'watch', label: 'Keep checking for events in the background every 10 min, even with the dashboard closed', kind: 'checkbox', default: false },
      {
        key: 'snapshots',
        label: 'Still image on page load',
        kind: 'select',
        options: [
          ['wired', 'Only for mains-powered cameras (default)'],
          ['all', 'All cameras — wakes battery cameras every 10 min'],
          ['off', 'Never'],
        ],
        default: 'wired',
      },
    ],
  },
  ...APP_WIDGETS,
  generic: {
    icon: '{}',
    name: 'Custom JSON',
    description: 'Fetch any JSON API and show chosen fields — for anything not built in yet.',
    component: GenericWidget,
    defaultW: 1,
    defaultTitle: 'Custom',
    fields: [
      { key: 'endpoint', label: 'JSON endpoint', kind: 'url', required: true, placeholder: 'http://host:port/api/status' },
      { key: 'headers', label: 'Headers (one per line, stored server-side)', kind: 'secret-textarea', placeholder: 'X-Api-Key: abc123' },
      {
        key: 'fields',
        label: 'Fields',
        kind: 'fields',
        hint: 'Path uses dots and [index], e.g. data.items[0].count',
      },
    ],
  },
};

/** Widget picker groups. Order here is the order shown in the editor. */
export const CATEGORIES = [
  { id: 'general', name: 'General', types: ['link', 'clock', 'weather', 'generic', 'prometheus'] },
  { id: 'infra', name: 'Infrastructure', types: ['docker', 'system', 'proxmox', 'uptimekuma', ...APP_CATEGORIES.infra] },
  { id: 'network', name: 'Network & DNS', types: ['pihole', 'adguard', 'tailscale', 'speedtest', ...APP_CATEGORIES.network] },
  { id: 'scryer', name: 'Scryer', types: ['scryer', 'scryerwanted'] },
  { id: 'media', name: 'Media', types: ['plex', 'jellyfin', 'sonarr', 'radarr', 'seerr', 'immich', ...APP_CATEGORIES.media] },
  { id: 'downloads', name: 'Downloads', types: ['weaver', 'qbittorrent', 'transmission', ...APP_CATEGORIES.downloads] },
  { id: 'home', name: 'Home & cameras', types: ['homeassistant', 'tapo', ...APP_CATEGORIES.home] },
  { id: 'apps', name: 'Apps & tools', types: APP_CATEGORIES.apps },
];
export const WIDGET_ORDER = CATEGORIES.flatMap((c) => c.types);
